#!/usr/bin/env python3
"""Generate runtime agent files from the canonical 00_Agents/*.md.

Outputs:
  .claude/agents/<name>.md     (verbatim copy; Claude Code reads frontmatter natively)
  .codex/agents/<name>.toml    (Codex custom agent; copy or symlink into ~/.codex/agents/)

Usage: python3 sync_agents.py [--root PATH] [--check]
  --check  exit 1 if outputs are out of date, write nothing (used by doctor)
"""
import argparse
import hashlib
import re
import sys
from pathlib import Path

HEADER = "# GENERATED by the cowork plugin (skills/doctor/scripts) from 00_Agents/{name}.md. Do not edit.\n"


def parse_frontmatter(text: str):
    m = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.S)
    if not m:
        return {}, text
    meta = {}
    for line in m.group(1).splitlines():
        if ":" in line:
            k, v = line.split(":", 1)
            meta[k.strip()] = v.strip()
    return meta, m.group(2)


def toml_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_toml(name: str, meta: dict, body: str) -> str:
    lines = [HEADER.format(name=name)]
    lines.append(f"name = {toml_str(meta.get('name', name))}")
    lines.append(f"description = {toml_str(meta.get('description', ''))}")
    if meta.get("model"):
        lines.append(f"# model hint from canonical file: {meta['model']} (map to a Codex model if desired)")
    lines.append("developer_instructions = '''")
    lines.append(body.strip())
    lines.append("'''")
    return "\n".join(lines) + "\n"


def render_claude(name: str, raw: str) -> str:
    # Keep frontmatter first (Claude Code requires it at top), then the generated marker.
    meta_block, body = re.match(r"^(---\n.*?\n---\n)(.*)$", raw, re.S).groups()
    return meta_block + "\n<!-- GENERATED from 00_Agents/" + name + ".md by sync-agents. Do not edit. -->\n" + body


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=".")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    root = Path(args.root).resolve()
    src = root / "00_Agents"
    if not src.is_dir():
        print(f"no canonical agents dir at {src}")
        return 0
    targets = {}
    for f in sorted(src.glob("*.md")):
        raw = f.read_text()
        meta, body = parse_frontmatter(raw)
        if not meta:
            print(f"WARN {f}: missing YAML frontmatter, skipped")
            continue
        name = meta.get("name", f.stem)
        targets[root / ".claude" / "agents" / f"{name}.md"] = render_claude(name, raw)
        targets[root / ".codex" / "agents" / f"{name}.toml"] = render_toml(name, meta, body)

    stale = []
    for path, content in targets.items():
        current = path.read_text() if path.exists() else None
        if current != content:
            stale.append(path)
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content)
    # Detect orphaned generated files (canonical deleted)
    orphans = []
    for d, ext in ((root / ".claude" / "agents", ".md"), (root / ".codex" / "agents", ".toml")):
        if d.is_dir():
            for f in d.glob(f"*{ext}"):
                if f not in targets and ("GENERATED" in f.read_text()[:400]):
                    orphans.append(f)

    if args.check:
        for p in stale:
            print(f"DRIFT {p.relative_to(root)}")
        for p in orphans:
            print(f"ORPHAN {p.relative_to(root)} (canonical source removed)")
        return 1 if (stale or orphans) else 0
    for p in stale:
        print(f"wrote {p.relative_to(root)}")
    for p in orphans:
        print(f"ORPHAN {p.relative_to(root)}: canonical source removed; delete it manually")
    if not stale:
        print("already in sync")
    return 0


if __name__ == "__main__":
    sys.exit(main())
